services:
  mysql:
    build: ./mysql/
    container_name: webmon-db
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d:ro
      - mysql_db:/var/lib/mysql:rw
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s
volumes:
  mysql_db:
