services:
  mysql:
    build: ./mysql/
    container_name: webmon-db
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d:ro
      - mysql_db:/var/lib/mysql:rw
    ports:
      - "3306:3306"
volumes:
  mysql_db:
